<!DOCTYPE HTML>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="description" content="C/C++ 安全编程要点：异常类的拷贝构造函数抛出异常违反异常处理机制，会导致程序异常终止。" />
  <link type="text/css" rel="stylesheet" href="../css/detail.css" />
  <link type="image/x-icon" rel="shortcut icon" href="../favicon.png" />
  <script src="../js/search.js"></script>
  <script src="../js/iconfont.js"></script>
  <title>异常类的拷贝构造函数不可抛出异常 - C/C++ 安全规则</title>
</head>
<div class="footer-holder">
<nav>
  <span class="nav-icon">☰</span>
  <ul class="nav-list">
    <li><a href="../index.html">首页</a></li>
    <li><a href="../index.html#rules-class-title">规则分类</a></li>
    <li><a href="./introduction.html">项目介绍</a></li>
  </ul>
  <div class="nav-stuff"></div>
  <div class="search-box">
    <input type="text" id="search-input" placeholder="Search..." onkeydown="onKeyDownForSearch(event)" />
    <img alt="search" id="search-icon" src="../img/search.svg" onclick="onClickSearchIcon(this)"/>
  </div>
  <span class="nav-ellipsis">•••</span>
</nav>
<article>
<header>
  <h1>异常类的拷贝构造函数不可抛出异常</h1>
  <div id="subtitle">
    <div id="subtitle-id">7.12 ID_throwWhileThrowing</div>
    <div id="subtitle-tags">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-standard"></use></svg><a class="rule-toc-link" href="../index.html#exception">目录</a> › <a class="rule-toc-link" href="./ID_exceptionInException.html">next</a> › <a class="rule-toc-link" href="./ID_throwInMove.html">previous</a>
    </div>
  </div>
  <hr class="solid-hr"/>
</header>
<main>
<p>异常类的拷贝构造函数抛出异常违反异常处理机制，会导致程序异常终止。</p>

<p>当抛出异常时，throw 表达式指定的异常对象会被复制，用以初始化相应 catch 子句的参数，如果在复制过程中又抛出异常便违反了异常处理机制，这种情况将直接引发 std::terminate 函数的执行，使程序异常终止。</p>

<p>示例：</p>
<pre><code>class E {
public:
    E() {}
    E(const E&amp;) {
        throw 0;    //<i> Non-compliant</i>
    }
};

int main() {
    try {
        E e0;
        throw e0;   //<i> Throw while throwing, calls std::terminate()</i>
    }
    catch (E&amp; e1) {
        ....
    }
}</code></pre>
<p>例中 catch 子句的参数 e1 引用由 e0 复制而成的临时对象，在复制过程中抛出的异常无法被捕获，会直接导致程序异常终止。</p>

</main>

<h3>相关</h3>
<div class="ref-items"><a href="./ID_exceptionInException.html" class="related-link">ID_exceptionInException</a></div>

<h3>依据</h3>
<div class="ref-items">ISO/IEC 14882:2003 15.1(3)
ISO/IEC 14882:2011 15.1(3 7)
ISO/IEC 14882:2017 18.1(3 7)</div>

<h3>参考</h3>
<div class="ref-items"><a href="http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e16-destructors-deallocation-swap-and-exception-type-copymove-construction-must-never-fail" target="_blank" class="related-link">C++ Core Guidelines E.16</a>
<a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR60-CPP.+Exception+objects+must+be+nothrow+copy+constructible" target="_blank" class="related-link">SEI CERT ERR60-CPP</a></div>
</article>
</div>
<footer>
  <a href="https://www.apache.org/licenses/LICENSE-2.0">Copyright©2024 360 Security Technology Inc., Licensed under the Apache-2.0 license.</a>
</footer>
</html>
