<!DOCTYPE HTML>
<html lang="zh">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <link type="text/css" rel="stylesheet" href="../css/detail.css"/>
  <link type="image/x-icon" rel="shortcut icon" href="../favicon.png"/>
  <title>由 noexcept 标记的函数不可产生未处理的异常 - C/C++ 安全规则</title>
</head>
<script src="../js/iconfont.js"></script>
<article>
<header>
  <h1>由 noexcept 标记的函数不可产生未处理的异常</h1>
  <div id="subtitle">
    <div id="subtitle-id">ID_throwInNoexcept</div>
    <div id="subtitle-tags">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-standard"></use></svg> <a class="nav-link" href="../index.html">Home</a> › <a class="nav-link" href="./ID_diamondExceptionInheritance.html">next</a> › <a class="nav-link" href="./ID_throwInHash.html">previous</a>
    </div>
  </div>
  <hr class="dashed-hr"/>
</header>
<div class="main-p">
由 noexcept 标记的函数产生未被处理的异常属于逻辑错误，会引发 std::terminate 函数的执行，使程序异常终止。

程序异常终止所产生的问题可参见 <a href="./ID_uncaughtException.html" target="_blank" class="dashed-link">ID_uncaughtException</a> 的进一步讨论。

示例：
<div class="code">void foo() noexcept
{
    throw Exception();   //<span class="comment"> Non-compliant, calls std::terminate()</span>
}
</div>
应处理相关异常或修正异常说明：
<div class="code">void foo() noexcept(false)
{
    throw Exception();   //<span class="comment"> Compliant</span>
}</div>

</div>

<h3>相关</h3>
<hr class="dashed-hr"/>
<p class="main-p"><a href="./ID_uncaughtException.html" target="_blank" class="related-link">ID_uncaughtException</a>

</p>

<h3>依据</h3>
<hr class="dashed-hr"/>
<p class="main-p">ISO/IEC 14882:2011 15.4(9)
ISO/IEC 14882:2017 18.4(5)

</p>

<h3>参考</h3>
<hr class="dashed-hr"/>
<p class="main-p">SEI CERT ERR55-CPP

</p>
</article>
</html>
